info:
  app:
  name: dogood-scores-user
  version: 1.0.0
  description: API service for user score management

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dogood
    username: root
    password: root

openapi:
  enabled: true
  info:
    title: dogood-scores-user
    description: API service for user score management
    version: 1.0.0
    contact:
      name: Dogood
      email: contact_support@dogood.com
      license:
        name: Copyright Dogood

#For sorting endpoints alphabetically
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha